# Лабораторна робота №1
**Тема:** Засоби реалізації математичного моделювання та аналізу даних

## Завдання 1
**№1 Виконати операції для роботи з обʼєктом Pandas.DataFrame**

In [50]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('netflix_titles.csv')
df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [10]:
df.tail(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [22]:
df.shape # визначення розміру (спочатку рядки, потім стовпці)

(8807, 12)

In [14]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [15]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [16]:
df[['title', 'release_year']].head()

                   title  release_year
0   Dick Johnson Is Dead          2020
1          Blood & Water          2021
2              Ganglands          2021
3  Jailbirds New Orleans          2021
4           Kota Factory          2021

In [18]:
df.iloc[-1] # повернути значення останього рядка

show_id                                                     s8807
type                                                        Movie
title                                                      Zubaan
director                                              Mozez Singh
cast            Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
country                                                     India
date_added                                          March 2, 2019
release_year                                                 2015
rating                                                      TV-14
duration                                                  111 min
listed_in          Dramas, International Movies, Music & Musicals
description     A scrappy but poor boy worms his way into a ty...
Name: 8806, dtype: object

In [20]:
df.iloc[-1,2] # повернути значення на перетині рядка і стовпця

'Zubaan'

In [24]:
df.loc[1,['title']]

title    Blood & Water
Name: 1, dtype: object

In [29]:
df.iloc[0:6,0:5]

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K..."
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H..."

In [33]:
df.loc[0:6,'show_id':'cast']

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K..."
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ..."

In [34]:
df.describe() # середнє, макс і мін значення

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [36]:
df.describe(include=[object]) # визначення статистики

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,3207,1793,362,4

In [41]:
df['duration'].value_counts(normalize=True) # Знаходження відсоткового співвідношення кожної тривалості контенту

duration
1 Season     0.203657
2 Seasons    0.048274
3 Seasons    0.022603
90 min       0.017265
94 min       0.016583
               ...
16 min       0.000114
186 min      0.000114
193 min      0.000114
189 min      0.000114
191 min      0.000114
Name: proportion, Length: 220, dtype: float64

In [50]:
df['director'].unique() # отримання масиву всіх унікальних (неповторюваних) значень

array(['Kirsten Johnson', nan, 'Julien Leclercq', ..., 'Majid Al Ansari',
       'Peter Hewitt', 'Mozez Singh'], dtype=object)

In [51]:
df.sample(frac=0.1) # отримати вибірку 10% від загальної кількості рядків

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8591,s8592,Movie,Time Please,Sameer Vidwans,"Priya Bapat, Siddarth Jadhav, Umesh Kamat, Sai...",India,"January 1, 2018",2013,TV-14,125 min,"Comedies, Dramas, International Movies","Personality differences, an old friend and a p..."
40,s41,TV Show,He-Man and the Masters of the Universe,NaN,"Yuri Lowenthal, Kimberly Brooks, Antony Del Ri...",United States,"September 16, 2021",2021,TV-Y7,1 Season,"Kids' TV, TV Sci-Fi & Fantasy",Mighty teen Adam and his heroic squad of misfi...
3236,s3237,TV Show,Once Upon A Time In Lingjian Mountain,NaN,"Xu Kai, Sandrine Pinna, Ryan Zhu, Gao Yuer, Cr...",China,"November 23, 2019",2019,TV-14,1 Season,"International TV Shows, TV Comedies, TV Sci-Fi...","As the nine continents face a crisis, a young ..."
3848,s3849,TV Show,Cinta Teruna Kimchi,NaN,"Nazim Othman, Johan As'ari, Nur Risteena, Nien...",NaN,"May 8, 2019",2016,TV-PG,1 Season,"International TV Shows, TV Dramas",When a young man determines to discover his fa...
1573,s1574,TV Show,The Expanding Universe of Ashley Garcia,NaN,"Paulina Chávez, Jencarlos Canela",United States,"December 9, 2020",2020,TV-PG,3 Seasons,"Kids' TV, TV Comedies, Teen TV Shows",15-year-old scientist Ashley Garcia explores t...
...,...,...,...,...,...,...,...,...,...,...,...,...
5600,s5601,Movie,A Heavy Heart,Thomas Stuber,"Peter Kurth, Lena Lauzemis, Lina Wendel, Edin ...",Germany,"February 15, 2017",2015,TV-MA,109 min,"Dramas, Independent Movies, International Movies","Long past his heyday, a still-virile boxer tri..."
8535,s8536,Movie,The Trigger Effect,David Koepp,"Kyle MacLachlan, Elisabeth Shue, Dermot Mulron...",United States,"January 1, 2018",1996,R,94 min,Thrillers,When a power failure throws their suburban tow...
4050,s4051,Movie,Weapon of Choice,Fritz Ofner,NaN,"Austria, Iraq, United States","March 2, 2019",2018,TV-MA,89 min,"Documentaries, International Movies",Speaking to retailers and owners of the Glock ...
698,s699,Movie,Fan Girl,Antoinette Jadaone,"Charlie Dizon, Paulo Avelino",Philippines,"June 17, 2021",2020,TV-MA,101 min,"Dramas, Independent Movies, International Movies",An infatuated fan finds an unexpected way to m...
4208,s4209,Movie,GODZILLA The Planet Eater,"Kobun Shizuno, Hiroyuki Seshita","Mamoru Miyano, Takahiro Sakurai, Kana Hanazawa...",Japan,"January 9, 2019",2018,TV-PG,91 min,"Action & Adventure, Anime Features, Internatio...","With the earth alliance weakened, Haruo weighs..."

In [52]:
df.to_csv('netflix_sample.csv', index=False)

**№2 Виконати операції групування даних**

In [57]:
df.groupby(['release_year']) # створення групи

In [58]:
df.groupby(['release_year']).groups

{1925: [4250], 1942: [7790, 8205], 1943: [8660, 8739, 8763], 1944: [8419, 8436, 8640], 1945: [1331, 7219, 7575, 7930], 1946: [7294, 7743], 1947: [8587], 1954: [1699, 2375], 1955: [7839, 7954, 8506], 1956: [2369, 6784], 1958: [2368, 6431, 6853], 1959: [542], 1960: [5220, 6395, 7133, 7637], 1961: [177], 1962: [5400, 7332, 7530], 1963: [2373, 8541], 1964: [1126, 7932], 1965: [6619, 8249], 1966: [5391], 1967: [6358, 6533, 8189, 8717, 8735], 1968: [6473, 7659, 7894], 1969: [5461, 8635], 1970: [2376, 8260], 1971: [5396, 5545, 6031, 6746, 8745], 1972: [716, 4550, 6254, 7224, 8127], 1973: [2491, 5300, 6350, 6448, 6496, 6701, 7122, 7130, 7431, 8792], 1974: [4551, 5303, 6111, 7058, 7825, 8401, 8527], 1975: [41, 1817, 4217, 5549, 6485, 7007, 8306], 1976: [529, 819, 2492, 5295, 6423, 6960, 7330, 7879, 8063], 1977: [5612, 6030, 6130, 6549, 6781, 8136, 8237], 1978: [42, 5186, 6284, 6771, 6893, 8303, 8514], 1979: [1719, 2365, 2487, 4552, 4861, 5704, 6674, 6864, 7367, 7880, 8332], 1980: [175, 605, 1831, 2723, 5079, 7188, 7752, 7755, 7820, 7860, 8142], 1981: [670, 689, 814, 1055, 2482, 2490, 7072, 7160, 7384, 7588, 8105, 8290, 8748], 1982: [131, 671, 1826, 1862, 2367, 2484, 4547, 6255, 6765, 7171, 7284, 7557, 7881, 7913, 7944, 8266, 8408], 1983: [43, 454, 5296, 6665, 7311, 7393, 7419, 7651, 7917, 8231, 8709], 1984: [166, 601, 810, 2488, 2721, 5309, 7073, 7519, 7678, 7794, 7844, 8435], 1985: [303, 2489, 6614, 6705, 7433, 7827, 7878, 7882, 8569, 8628], 1986: [155, 176, 333, 602, 2740, 5080, 5130, 5943, 5944, 6151, 7410, 7751, 7993], 1987: [44, 1450, 2738, 4237, 5947, 6913, 7252, 7370], 1988: [579, 672, 1254, 1461, 5290, 5299, 5942, 5946, 5949, 6468, 6970, 7203, 7428, 7697, 7722, 7958, 8434, 8572], 1989: [139, 603, 928, 1761, 2366, 4233, 4554, 5304, 5948, 6013, 6116, 6548, 6636, 7071, 7387, 8523], 1990: [144, 1251, 1621, 1861, 2317, 2715, 4244, 5945, 5951, 6704, 6844, 6880, 7175, 7310, 7335, 7708, 7721, 7883, 8004, 8160, 8621, 8644], 1991: [145, 343, 354, 1822, 4229, 4238, 4239, 4245, 5131, 5950, 5952, 6152, 6347, 6570, 8050, 8159, 8433], 1992: [160, 325, 586, 955, 1015, 4231, 5481, 5570, 5908, 6248, 6267, 6415, 6428, 6429, 6456, 6593, 7153, 7305, 7711, 7714, 8103, 8261, 8383], 1993: [7, 135, 183, 267, 305, 326, 568, 813, 1469, 2301, 2725, 4232, 4946, 5447, 5455, 6032, 6493, 6798, 7183, 7562, 7735, 7957, 7964, 8039, 8148, 8203, 8409, 8449], 1994: [67, 114, 134, 146, 344, 946, 1768, 2361, 2545, 2957, 5408, 5482, 5821, 6197, 6469, 6792, 7347, 7802, 8259, 8304, 8489, 8764], 1995: [253, 314, 342, 358, 567, 581, 3724, 5460, 5485, 6211, 6220, 6246, 6866, 7018, 7103, 7193, 7357, 7620, 7900, 8187, 8361, 8598, 8622, 8629, 8669], 1996: [22, 161, 179, 818, 1124, 2483, 5499, 5500, 6060, 6266, 6641, 6719, 7177, 7210, 7455, 7785, 7793, 7824, 8038, 8106, 8256, 8301, 8535, 8614], 1997: [26, 170, 559, 562, 564, 600, 782, 793, 798, 868, 1353, 1453, 2354, 3728, 5960, 6188, 6260, 6301, 6450, 6562, 6633, 6711, 6851, 6962, 7015, 7113, 7144, 7213, 7303, 7442, 7484, 7589, 7706, 7783, 7961, 8448, 8473, 8603], 1998: [24, 149, 614, 615, 867, 1160, 2073, 2074, 2090, 2722, 2734, 3475, 3720, 4546, 4686, 5007, 5056, 5462, 5923, 6049, 6143, 6247, 6414, 6735, 6743, 6947, 7244, 7326, 7745, 7764, 7895, 7906, 7959, 8042, 8413, 8554], 1999: [150, 164, 332, 341, 443, 563, 595, 906, 1140, 1441, 1639, 1829, 1944, 2311, 2444, 2460, 2969, 4211, 5650, 6135, 6153, 6303, 6343, 6459, 6514, 6936, 7022, 7399, 7551, 7767, 7903, 7989, 8130, 8144, 8151, 8414, 8526, 8564, 8742], 2000: [180, 350, 359, 566, 593, 779, 952, 2173, 3472, 4545, 4723, 4956, 5098, 5245, 5953, 6006, 6147, 6154, 6311, 6437, 6440, 6543, 6643, 6753, 6912, 7013, 7247, 7316, 7702, 7766, 7801, 7955, 7962, 8196, 8305, 8722, 8729], 2001: [48, 54, 137, 168, 205, 584, 657, 776, 788, 797, 812, 995, 1019, 1121, 2731, 3062, 3131, 3910, 4092, 5571, 5574, 5672, 5811, 6123, 6163, 6221, 6322, 6337, 6715, 6722, 6884, 6949, 7121, 7170, 7544, 7782, 8074, 8214, 8446, 8498, 8602, 8607, 8623, 8768, 8770], 2002: [51, 194, 329, 561, 608, 951, 1138, 1305, 1750, 1866, 1937, 2001, 2069, 2399, 3276, 4108, 4189, 5179, 6062, 6081, 6229, 6305, 6309, 6488, 6522, 6588, 6609, 6610, 6694, 6703, 6826, 7090, 7156, 7411, 7443, 7517, 7695, 7701, 7744, 7784, 7994, 7996, 7997, 8075, 8110, 8405, 8486, 8531, 8540, 8725, 8766], 2003: [52, 122, 136, 158, 163, 172, 174, 201, 349, 604, 610, 651, 787, 942, 1051, 1426, 1825, 1922, 1941, 2596, 2732, 3263, 3284, 3913, 3914, 3915, 4413, 4792, 5095, 6007, 6164, 6212, 6299, 6359, 6447, 6550, 6567, 6639, 6654, 6655, 6754, 6795, 6806, 6837, 6886, 7089, 7189, 7197, 7275, 7439, 7481, 7710, 7769, 7912, 8055, 8076, 8166, 8317, 8404, 8415, 8416], 2004: [53, 63, 127, 200, 351, 357, 652, 799, 809, 891, 981, 1020, 1521, 1673, 1858, 1876, 2318, 2439, 2510, 3002, 3142, 3274, 3544, 3649, 3883, 4102, 4650, 4952, 5014, 5019, 5021, 5244, 6018, 6107, 6222, 6283, 6480, 6540, 6602, 6669, 6928, 6957, 7088, 7198, 7239, 7249, 7460, 7524, 7564, 7579, 7597, 7639, 7763, 7840, 7897, 7902, 8013, 8037, 8452, 8461, 8463, 8465, 8624, 8682], 2005: [61, 129, 151, 202, 319, 578, 722, 816, 931, 1149, 1314, 1364, 1422, 1423, 1818, 1832, 1848, 1893, 1916, 2512, 2621, 2632, 2729, 2845, 3148, 3476, 3897, 3911, 3917, 4553, 4583, 4737, 4745, 4955, 5542, 5815, 5822, 5977, 6204, 6289, 6376, 6446, 6466, 6510, 6634, 6843, 6852, 6878, 6926, 6977, 7032, 7079, 7135, 7150, 7152, 7174, 7208, 7360, 7386, 7503, 7532, 7590, 7772, 7830, 7901, 7938, 8047, 8152, 8174, 8183, 8188, 8228, 8284, 8333, 8346, 8557, 8668, 8689, 8767, 8793], 2006: [62, 169, 199, 335, 597, 606, 803, 804, 864, 926, 1043, 1102, 1256, 1261, 1519, 1548, 1616, 1622, 1624, 1721, 1851, 1865, 2340, 2434, 2435, 2441, 2501, 2509, 2612, 2633, 2658, 2730, 3068, 3133, 3351, 3514, 3541, 4007, 4080, 4107, 4429, 4447, 4470, 4732, 4790, 4966, 5132, 5294, 5572, 5751, 5957, 5992, 6103, 6120, 6205, 6217, 6296, 6427, 6482, 6497, 6577, 6680, 6692, 6724, 6755, 6870, 6982, 7023, 7094, 7109, 7172, 7186, 7262, 7356, 7422, 7553, 7669, 7687, 7724, 7748, 7768, 8086, 8101, 8128, 8226, 8272, 8380, 8396, 8454, 8469, 8476, 8555, 8655, 8757, 8773, 8805], 2007: [59, 142, 215, 327, 337, 460, 512, 753, 1022, 1456, 1827, 1943, 1945, 1946, 2009, 2314, 2429, 2504, 2519, 2592, 2863, 3057, 3139, 3349, 3650, 3988, 4017, 4378, 4431, 4440, 4449, 4747, 4797, 4858, 4871, 4954, 5008, 5192, 5298, 5648, 5854, 5939, 5956, 6085, 6176, 6270, 6298, 6327, 6370, 6511, 6604, 6611, 6710, 6793, 6797, 6847, 6909, 7005, 7085, 7520, 7527, 7581, 7592, 7638, 7690, 7692, 7694, 7704, 7728, 7770, 7923, 7967, 8067, 8126, 8138, 8158, 8185, 8223, 8229, 8285, 8316, 8372, 8551, 8553, 8611, 8612, 8694, 8802], 2008: [57, 167, 182, 188, 192, 195, 207, 322, 346, 451, 573, 591, 607, 791, 943, 956, 1018, 1111, 1144, 1266, 1327, 1332, 1359, 1707, 1714, 1940, 2072, 2180, 2403, 2433, 2438, 2505, 2582, 2614, 2637, 2720, 2902, 3020, 3058, 3145, 3223, 3240, 3333, 3647, 3691, 3870, 3973, 4010, 4065, 4112, 4235, 4247, 4349, 4421, 4451, 4454, 4464, 4543, 4573, 4579, 4600, 4721, 4838, 4893, 5018, 5194, 5386, 5632, 5748, 5753, 5802, 5823, 5824, 5826, 5873, 5959, 5962, 5981, 6063, 6097, 6268, 6271, 6354, 6421, 6503, 6517, 6530, 6637, 6672, 6718, 6748, 6767, 6790, 6813, 6842, 6888, 6901, 6927, 6986, 7055, ...], 2009: [58, 115, 313, 330, 347, 368, 371, 407, 415, 450, 594, 612, 777, 802, 858, 933, 947, 950, 1113, 1114, 1139, 1247, 1447, 1454, 1522, 1610, 1683, 1795, 1895, 1942, 2056, 2126, 2407, 2436, 2502, 2506, 2517, 2518, 2575, 2620, 2636, 2638, 2978, 3059, 3073, 3143, 3290, 3498, 3881, 4330, 4343, 4401, 4420, 4432, 4478, 4549, 4558, 4561, 4562, 4569, 4575, 4578, 4580, 4591, 4612, 4729, 4862, 4948, 4965, 5193, 5195, 5247, 5366, 5405, 5720, 5816, 5955, 5958, 5993, 6057, 6230, 6232, 6291, 6379, 6401, 6424, 6474, 6486, 6536, 6617, 6663, 6668, 6728, 6731, 6804, 6818, 6824, 6828, 6910, 7021, ...], 2010: [27, 60, 138, 156, 159, 206, 208, 315, 336, 340, 356, 360, 409, 419, 449, 502, 575, 592, 598, 609, 635, 792, 925, 927, 930, 932, 1017, 1021, 1118, 1135, 1179, 1215, 1358, 1387, 1508, 1623, 1675, 1677, 1928, 2039, 2041, 2374, 2425, 2493, 2497, 2544, 2619, 2630, 2635, 2701, 2745, 2843, 2915, 3141, 3271, 3323, 3340, 3663, 4150, 4151, 4228, 4345, 4427, 4433, 4455, 4610, 4613, 4724, 4727, 4731, 4795, 4800, 5096, 5191, 5393, 5484, 5510, 5548, 5583, 5602, 5749, 5767, 5794, 5805, 5814, 5874, 5954, 5976, 5990, 6044, 6074, 6075, 6087, 6101, 6227, 6235, 6239, 6262, 6276, 6290, ...], 2011: [56, 143, 210, 216, 217, 251, 316, 355, 408, 422, 423, 447, 574, 583, 784, 796, 801, 859, 863, 949, 970, 1016, 1255, 1257, 1264, 1413, 1421, 1459, 1467, 1485, 1538, 1539, 1547, 1674, 1679, 1957, 2071, 2079, 2265, 2279, 2288, 2290, 2323, 2442, 2615, 2634, 2641, 2852, 2860, 3005, 3016, 3134, 3136, 3149, 3272, 3664, 3700, 3741, 3760, 3834, 4008, 4047, 4246, 4249, 4261, 4277, 4290, 4329, 4337, 4424, 4453, 4466, 4587, 4588, 4719, 4720, 4736, 5322, 5347, 5362, 5389, 5403, 5467, 5649, 5669, 5727, 5803, 5820, 5914, 5941, 6012, 6019, 6041, 6053, 6054, 6056, 6070, 6073, 6131, 6180, ...], 2012: [46, 123, 204, 292, 308, 323, 383, 392, 414, 420, 424, 448, 528, 558, 611, 630, 702, 741, 775, 795, 800, 935, 1052, 1104, 1115, 1154, 1199, 1324, 1349, 1444, 1498, 1513, 1534, 1615, 1735, 1767, 1824, 1833, 1934, 2064, 2120, 2139, 2260, 2264, 2266, 2281, 2285, 2381, 2437, 2503, 2511, 2539, 2584, 2623, 2717, 2899, 3108, 3137, 3146, 3147, 3317, 3512, 3538, 3614, 3713, 3736, 3882, 4009, 4038, 4060, 4078, 4100, 4103, 4157, 4222, 4248, 4255, 4280, 4426, 4439, 4441, 4443, 4446, 4461, 4503, 4540, 4565, 4582, 4586, 4605, 4611, 4616, 4683, 4728, 4733, 4735, 4746, 4786, 4787, 4788, ...], 2013: [28, 29, 76, 124, 209, 285, 301, 302, 321, 353, 374, 406, 410, 411, 412, 413, 416, 555, 718, 747, 778, 786, 916, 939, 941, 979, 1005, 1029, 1033, 1101, 1153, 1158, 1175, 1216, 1239, 1240, 1283, 1396, 1452, 1465, 1537, 1566, 1569, 1602, 1664, 1692, 1694, 1710, 1784, 1787, 1819, 1905, 1938, 1971, 1974, 2003, 2102, 2267, 2268, 2270, 2276, 2277, 2289, 2291, 2385, 2571, 2581, 2708, 2724, 3008, 3090, 3135, 3262, 3270, 3280, 3320, 3325, 3487, 3610, 3648, 3697, 3723, 3869, 3880, 3908, 3923, 3956, 4073, 4074, 4216, 4234, 4333, 4348, 4423, 4438, 4442, 4444, 4445, 4450, 4457, ...], 2014: [50, 66, 140, 178, 211, 228, 264, 338, 365, 421, 496, 654, 723, 726, 740, 743, 752, 808, 845, 865, 940, 969, 978, 1011, 1053, 1191, 1197, 1243, 1267, 1406, 1446, 1463, 1472, 1543, 1608, 1611, 1612, 1613, 1697, 1820, 1843, 1939, 1976, 1982, 1986, 2010, 2014, 2121, 2125, 2135, 2142, 2175, 2274, 2278, 2280, 2282, 2287, 2312, 2377, 2402, 2419, 2450, 2463, 2496, 2525, 2586, 2726, 2728, 2737, 2747, 2809, 2854, 2885, 2946, 2965, 2967, 3038, 3054, 3112, 3190, 3260, 3304, 3314, 3315, 3339, 3371, 3423, 3542, 3606, 3611, 3613, 3620, 3737, 3777, 3809, 3876, 3905, 3922, 3990, 4000, ...], 2015: [69, 116, 133, 141, 154, 173, 257, 269, 345, 405, 417, 474, 494, 522, 530, 535, 656, 667, 695, 759, 760, 789, 790, 815, 817, 846, 980, 982, 984, 985, 990, 1001, 1027, 1056, 1119, 1148, 1208, 1211, 1229, 1263, 1362, 1618, 1654, 1676, 1863, 1950, 1972, 2049, 2214, 2271, 2272, 2273, 2286, 2309, 2339, 2383, 2464, 2529, 2568, 2574, 2678, 2680, 2716, 2718, 2735, 2879, 2881, 2884, 2903, 2905, 2924, 2958, 2990, 3018, 3021, 3061, 3071, 3072, 3114, 3115, 3125, 3126, 3128, 3132, 3203, 3230, 3239, 3261, 3316, 3322, 3324, 3327, 3336, 3420, 3421, 3582, 3609, 3612, 3618, 3619, ...], 2016: [104, 152, 153, 203, 212, 263, 281, 306, 328, 352, 476, 486, 510, 527, 582, 590, 650, 655, 708, 733, 828, 843, 872, 953, 977, 986, 1013, 1038, 1040, 1041, 1064, 1086, 1120, 1129, 1133, 1141, 1203, 1219, 1259, 1284, 1321, 1333, 1397, 1404, 1434, 1506, 1536, 1540, 1565, 1582, 1678, 1680, 1689, 1729, 1744, 1764, 1786, 1838, 1845, 1889, 1891, 1908, 1909, 1912, 1953, 1964, 1967, 1969, 1975, 1997, 2025, 2026, 2060, 2066, 2067, 2092, 2100, 2123, 2138, 2148, 2160, 2195, 2206, 2238, 2244, 2269, 2306, 2333, 2382, 2418, 2447, 2455, 2466, 2555, 2605, 2613, 2616, 2618, 2646, 2677, ...], 2017: [38, 89, 105, 118, 128, 162, 171, 191, 445, 446, 489, 491, 511, 517, 806, 807, 866, 904, 911, 914, 929, 937, 976, 989, 1007, 1035, 1036, 1071, 1078, 1112, 1125, 1128, 1130, 1131, 1132, 1134, 1142, 1194, 1292, 1307, 1336, 1337, 1415, 1457, 1458, 1470, 1526, 1619, 1647, 1661, 1690, 1691, 1771, 1776, 1805, 1821, 1823, 1849, 1867, 1884, 1890, 1899, 1903, 1965, 1966, 2020, 2027, 2042, 2062, 2116, 2172, 2179, 2191, 2223, 2296, 2348, 2350, 2411, 2427, 2428, 2430, 2446, 2452, 2453, 2454, 2520, 2535, 2611, 2617, 2631, 2702, 2704, 2706, 2712, 2744, 2755, 2789, 2801, 2803, 2831, ...], 2018: [21, 37, 73, 94, 96, 107, 157, 244, 259, 265, 288, 362, 492, 513, 525, 531, 536, 537, 541, 557, 585, 588, 633, 659, 661, 662, 668, 675, 678, 679, 681, 704, 751, 754, 821, 824, 839, 885, 892, 921, 922, 934, 944, 948, 954, 962, 971, 1006, 1047, 1059, 1072, 1073, 1076, 1081, 1103, 1107, 1145, 1159, 1252, 1270, 1271, 1288, 1297, 1303, 1309, 1322, 1350, 1355, 1356, 1367, 1377, 1379, 1399, 1428, 1480, 1496, 1510, 1524, 1544, 1555, 1583, 1599, 1614, 1620, 1625, 1626, 1628, 1631, 1644, 1662, 1682, 1695, 1709, 1724, 1730, 1738, 1739, 1747, 1753, 1755, ...], 2019: [87, 90, 100, 121, 165, 232, 289, 334, 348, 378, 389, 390, 418, 425, 427, 435, 456, 461, 462, 469, 475, 495, 507, 508, 509, 514, 515, 523, 524, 526, 532, 534, 553, 569, 572, 576, 589, 596, 599, 616, 620, 622, 632, 634, 649, 663, 673, 674, 676, 694, 701, 705, 745, 773, 780, 794, 822, 823, 901, 917, 938, 958, 974, 987, 1008, 1010, 1014, 1042, 1046, 1049, 1063, 1065, 1068, 1074, 1077, 1106, 1117, 1137, 1246, 1253, 1268, 1276, 1295, 1316, 1320, 1330, 1354, 1357, 1361, 1363, 1365, 1381, 1382, 1385, 1407, 1417, 1443, 1464, 1475, 1477, ...], 2020: [0, 16, 17, 32, 34, 47, 78, 84, 103, 119, 126, 148, 189, 227, 229, 250, 256, 258, 260, 266, 268, 282, 294, 298, 324, 331, 367, 391, 429, 433, 434, 438, 473, 480, 498, 501, 505, 518, 519, 539, 540, 543, 545, 548, 549, 552, 554, 565, 587, 613, 619, 621, 627, 629, 664, 665, 666, 669, 677, 680, 688, 698, 709, 712, 713, 721, 727, 756, 769, 774, 825, 849, 856, 860, 875, 886, 887, 893, 898, 899, 907, 913, 915, 920, 924, 936, 945, 973, 991, 992, 994, 1000, 1009, 1030, 1031, 1034, 1039, 1045, 1048, 1054, ...], 2021: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20, 23, 25, 30, 31, 33, 35, 36, 39, 40, 45, 49, 55, 64, 65, 68, 70, 71, 72, 74, 75, 77, 79, 80, 81, 82, 83, 85, 86, 88, 91, 92, 93, 95, 97, 98, 99, 101, 102, 106, 108, 109, 110, 111, 112, 113, 117, 120, 125, 130, 132, 147, 181, 184, 185, 186, 187, 190, 193, 196, 197, 198, 213, 214, 218, 219, 220, 221, 222, 223, 224, 225, 226, 230, 231, 233, 234, 235, 236, 237, 238, 239, 240, 241, ...]}

In [59]:
df.groupby(['release_year']).first() # вивести перший рядок для кожного унікального року

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
release_year,,,,,,,,,,,
1925,s4251,TV Show,Pioneers: First Women Filmmakers*,None,None,None,"December 30, 2018",TV-14,1 Season,TV Shows,This collection restores films from women who ...
1942,s7791,Movie,Prelude to War,Frank Capra,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
1943,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,None,United States,"March 31, 2017",TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
1944,s8420,Movie,The Memphis Belle: A Story of a\nFlying Fortress,William Wyler,Burgess Meredith,United States,"March 31, 2017",TV-PG,40 min,"Classic Movies, Documentaries",This documentary centers on the crew of the B-...
1945,s1332,TV Show,Five Came Back: The Reference Films,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"February 9, 2021",TV-MA,1 Season,TV Shows,This collection includes 12 World War II-era p...
...,...,...,...,...,...,...,...,...,...,...,...
2017,s39,Movie,Birth of the Dragon,George Nolfi,"Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...","China, Canada, United States","September 16, 2021",PG-13,96 min,"Action & Adventure, Dramas",A young Bruce Lee angers kung fu traditionalis...
2018,s22,TV Show,Resurrection: Ertugrul,Kemi Adetiba,"Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar...",Turkey,"September 22, 2021",TV-14,5 Seasons,"International TV Shows, TV Action & Adventure,...",When a good deed unwittingly endangers his cla...
2019,s88,TV Show,Titipo Titipo,Alice Waddington,"Jeon Hae-ri, Kim Eun-ah, Hong Bum-ki, Nam Do-h...","Spain, United States","September 10, 2021",TV-Y,2 Seasons,"Kids' TV, Korean TV Shows",Titipo the train is out to prove that he's got...
2020,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",United States,"September 25, 2021",PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
2021,s2,TV Show,Blood & Water,Julien Leclercq,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [61]:
df.groupby(['release_year'])[['duration']].count()

              duration
release_year
1925                 1
1942                 2
1943                 3
1944                 3
1945                 4
...                ...
2017              1031
2018              1147
2019              1030
2020               953
2021               592

[74 rows x 1 columns]

In [64]:
df.groupby(['release_year']).agg({
    'type': 'count',
    'rating': 'first'
})

              type rating
release_year
1925             1  TV-14
1942             2  TV-14
1943             3  TV-PG
1944             3  TV-PG
1945             4  TV-MA
...            ...    ...
2017          1032  PG-13
2018          1147  TV-14
2019          1030   TV-Y
2020           953  PG-13
2021           592  TV-MA

[74 rows x 2 columns]

In [65]:
df.groupby(['release_year']).agg({
    'director': ['count', 'nunique'],
    'title': 'first'
}) # nunique кількість унікальних записів

             director          \
                count nunique
release_year
1925                0       0
1942                2       2
1943                3       3
1944                3       3
1945                3       3
...               ...     ...
2017              773     726
2018              760     713
2019              629     591
2020              548     516
2021              297     285

                                                         title
                                                         first
release_year
1925                         Pioneers: First Women Filmmakers*
1942                                            Prelude to War
1943             Undercover: How to Operate Behind Enemy Lines
1944          The Memphis Belle: A Story of a\nFlying Fortress
1945                       Five Came Back: The Reference Films
...                                                        ...
2017                                       Birth of the Dragon
2018                                    Resurrection: Ertugrul
2019                                             Titipo Titipo
2020                                      Dick Johnson Is Dead
2021                                             Blood & Water

[74 rows x 3 columns]

In [67]:
df.groupby(['release_year']).agg({
    'title': 'count',
    'listed_in': lambda x: x.mode()[0]
}) # найпопулярніше значення

              title                      listed_in
release_year
1925              1                       TV Shows
1942              2  Classic Movies, Documentaries
1943              3                  Documentaries
1944              3  Classic Movies, Documentaries
1945              4  Classic Movies, Documentaries
...             ...                            ...
2017           1032                  Documentaries
2018           1147                Stand-Up Comedy
2019           1030                Stand-Up Comedy
2020            953   Dramas, International Movies
2021            592                       Kids' TV

[74 rows x 2 columns]

**Виконати операції перетворення ознак**

In [69]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [72]:
type_mapping = {'Movie': 1, 'TV Show': 2}
df['type'].map(type_mapping).head()

0    1
1    2
2    2
3    2
4    2
Name: type, dtype: int64

In [77]:
df['release_year'].apply(lambda x: 2026 - x).head()

0    6
1    5
2    5
3    5
4    5
Name: release_year, dtype: int64

**№3 Виконати всі операції над кількома таблиями**

In [10]:
imdb = pd.read_csv('imdb_movies.csv')
amazon = pd.read_csv('amazon_prime_titles.csv')

In [15]:
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [16]:
imdb.head(2)

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU

In [17]:
amazon.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...

In [23]:
pd.merge(df, imdb, left_on=['title'], right_on=['names']) # Метод merge об'єднує дві таблиці на основі спільних значень

,show_id,type,title,director,cast,country_x,date_added,release_year,rating,duration,...,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country_y
0,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,...,78.0,"Animation, Family, Fantasy, Comedy, Adventure",Equestria's divided. But a bright-eyed hero be...,"Vanessa Hudgens, Sunny Starscout (voice), Kimi...",My Little Pony: A New Generation,Released,English,38211149.2,4100000.0,AU
1,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,...,71.0,Drama,A woman adjusting to life after a loss contend...,"Melissa McCarthy, Lilly Maynard, Chris O'Dowd,...",The Starling,Released,English,100000000.0,369861963.8,US
2,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,...,69.0,"Comedy, Drama",When the clever but socially-awkward Tetê join...,"Klara Castanho, Tetê, Gabriel Lima, Davi, Júli...",Confissões de uma Garota Excluída,Released,Portuguese,65500000.0,455599297.6,BR
3,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,...,60.0,Thriller,"When a husband and wife move to a small town, ...","Freida Pinto, Meera Parsons, Logan Marshall-Gr...",Intrusion,Released,English,82000000.0,618157116.2,US
4,s24,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ...",NaN,"September 21, 2021",2021,TV-Y,61 min,...,58.0,"Animation, Family",From arcade games to sled days and hiccup cure...,"Maisie Benson, , Paul Killam, , Kerry Gudjohns...",Go! Go! Cory Carson: Chrissy Takes the Wheel,Released,English,93000000.0,477850338.2,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1636,s8791,Movie,You Don't Mess with the Zohan,Dennis Dugan,"Adam Sandler, John Turturro, Emmanuelle Chriqu...",United States,"September 1, 2019",2008,UR,113 min,...,57.0,"Comedy, Action",An Israeli counterterrorism soldier with a sec...,"Adam Sandler, Zohan Dvir, Emmanuelle Chriqui, ...",You Don't Mess with the Zohan,Released,English,90000000.0,204313400.0,AU
1637,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,...,58.0,"Comedy, Drama",A divorced writer from the Midwest returns to ...,"Charlize Theron, Mavis Gary, Patton Oswalt, Ma...",Young Adult,Released,English,12000000.0,22750356.0,AU
1638,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,...,75.0,"Crime, Drama, Mystery, Thriller",A cartoonist teams up with an ace reporter and...,"Jake Gyllenhaal, Robert Graysmith, Mark Ruffal...",Zodiac,Released,English,85000000.0,83080084.0,AU
1639,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,...,73.0,"Comedy, Horror",Columbus has made a habit of running from what...,"Woody Harrelson, Tallahassee, Jesse Eisenberg,...",Zombieland,Released,English,23600000.0,102236596.0,AU
1640,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,...,54.0,"Family, Comedy, Adventure, Action, Science Fic...",Jack Shepard is an out-of-shape auto shop owne...,"Tim Allen, Jack Sheppard, Courteney Cox, Marsh...",Zoom,Released,English,35000000.0,12506188.0,AU

In [25]:
pd.merge(df, imdb, left_on=['title'], right_on=['names'], how='inner') # inner – дані які є одночасно в двох датасетахpd.merge(df, imdb, left_on=['title'], right_on=['names'], how='inner')

,show_id,type,title,director,cast,country_x,date_added,release_year,rating,duration,...,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country_y
0,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,...,78.0,"Animation, Family, Fantasy, Comedy, Adventure",Equestria's divided. But a bright-eyed hero be...,"Vanessa Hudgens, Sunny Starscout (voice), Kimi...",My Little Pony: A New Generation,Released,English,38211149.2,4100000.0,AU
1,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,...,71.0,Drama,A woman adjusting to life after a loss contend...,"Melissa McCarthy, Lilly Maynard, Chris O'Dowd,...",The Starling,Released,English,100000000.0,369861963.8,US
2,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,...,69.0,"Comedy, Drama",When the clever but socially-awkward Tetê join...,"Klara Castanho, Tetê, Gabriel Lima, Davi, Júli...",Confissões de uma Garota Excluída,Released,Portuguese,65500000.0,455599297.6,BR
3,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,...,60.0,Thriller,"When a husband and wife move to a small town, ...","Freida Pinto, Meera Parsons, Logan Marshall-Gr...",Intrusion,Released,English,82000000.0,618157116.2,US
4,s24,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ...",NaN,"September 21, 2021",2021,TV-Y,61 min,...,58.0,"Animation, Family",From arcade games to sled days and hiccup cure...,"Maisie Benson, , Paul Killam, , Kerry Gudjohns...",Go! Go! Cory Carson: Chrissy Takes the Wheel,Released,English,93000000.0,477850338.2,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1636,s8791,Movie,You Don't Mess with the Zohan,Dennis Dugan,"Adam Sandler, John Turturro, Emmanuelle Chriqu...",United States,"September 1, 2019",2008,UR,113 min,...,57.0,"Comedy, Action",An Israeli counterterrorism soldier with a sec...,"Adam Sandler, Zohan Dvir, Emmanuelle Chriqui, ...",You Don't Mess with the Zohan,Released,English,90000000.0,204313400.0,AU
1637,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,...,58.0,"Comedy, Drama",A divorced writer from the Midwest returns to ...,"Charlize Theron, Mavis Gary, Patton Oswalt, Ma...",Young Adult,Released,English,12000000.0,22750356.0,AU
1638,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,...,75.0,"Crime, Drama, Mystery, Thriller",A cartoonist teams up with an ace reporter and...,"Jake Gyllenhaal, Robert Graysmith, Mark Ruffal...",Zodiac,Released,English,85000000.0,83080084.0,AU
1639,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,...,73.0,"Comedy, Horror",Columbus has made a habit of running from what...,"Woody Harrelson, Tallahassee, Jesse Eisenberg,...",Zombieland,Released,English,23600000.0,102236596.0,AU
1640,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,...,54.0,"Family, Comedy, Adventure, Action, Science Fic...",Jack Shepard is an out-of-shape auto shop owne...,"Tim Allen, Jack Sheppard, Courteney Cox, Marsh...",Zoom,Released,English,35000000.0,12506188.0,AU

In [27]:
pd.merge(df, imdb, left_on=['title'], right_on=['names'], how='left', indicator=True) # indicator – додає стовпець з данимим звідки додалась інформація

,show_id,type,title,director,cast,country_x,date_added,release_year,rating,duration,...,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country_y,_merge
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8964,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,...,"Crime, Drama, Mystery, Thriller",A cartoonist teams up with an ace reporter and...,"Jake Gyllenhaal, Robert Graysmith, Mark Ruffal...",Zodiac,Released,English,85000000.0,83080084.0,AU,both
8965,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8966,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,...,"Comedy, Horror",Columbus has made a habit of running from what...,"Woody Harrelson, Tallahassee, Jesse Eisenberg,...",Zombieland,Released,English,23600000.0,102236596.0,AU,both
8967,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,...,"Family, Comedy, Adventure, Action, Science Fic...",Jack Shepard is an out-of-shape auto shop owne...,"Tim Allen, Jack Sheppard, Courteney Cox, Marsh...",Zoom,Released,English,35000000.0,12506188.0,AU,both
8968,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [31]:
df.reset_index(inplace=True)
imdb.reset_index(inplace=True)

In [32]:
df.set_index('title', inplace=True)
imdb.set_index('names', inplace=True) # зробити звичайні стовпці індексами

In [34]:
df.join(imdb, lsuffix='_netflix', rsuffix='_imdb', how='inner') # обґєднуємо за індексами

,show_id,type,director,cast,country_netflix,date_added,release_year,rating,duration,listed_in,...,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country_imdb
title,,,,,,,,,,,,,,,,,,,,,
My Little Pony: A New Generation,s7,Movie,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,...,78.0,"Animation, Family, Fantasy, Comedy, Adventure",Equestria's divided. But a bright-eyed hero be...,"Vanessa Hudgens, Sunny Starscout (voice), Kimi...",My Little Pony: A New Generation,Released,English,38211149.2,4100000.0,AU
The Starling,s10,Movie,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",...,71.0,Drama,A woman adjusting to life after a loss contend...,"Melissa McCarthy, Lilly Maynard, Chris O'Dowd,...",The Starling,Released,English,100000000.0,369861963.8,US
Confessions of an Invisible Girl,s14,Movie,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",...,69.0,"Comedy, Drama",When the clever but socially-awkward Tetê join...,"Klara Castanho, Tetê, Gabriel Lima, Davi, Júli...",Confissões de uma Garota Excluída,Released,Portuguese,65500000.0,455599297.6,BR
Intrusion,s19,Movie,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,...,60.0,Thriller,"When a husband and wife move to a small town, ...","Freida Pinto, Meera Parsons, Logan Marshall-Gr...",Intrusion,Released,English,82000000.0,618157116.2,US
Go! Go! Cory Carson: Chrissy Takes the Wheel,s24,Movie,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ...",NaN,"September 21, 2021",2021,TV-Y,61 min,Children & Family Movies,...,58.0,"Animation, Family",From arcade games to sled days and hiccup cure...,"Maisie Benson, , Paul Killam, , Kerry Gudjohns...",Go! Go! Cory Carson: Chrissy Takes the Wheel,Released,English,93000000.0,477850338.2,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Don't Mess with the Zohan,s8791,Movie,Dennis Dugan,"Adam Sandler, John Turturro, Emmanuelle Chriqu...",United States,"September 1, 2019",2008,UR,113 min,"Action & Adventure, Comedies",...,57.0,"Comedy, Action",An Israeli counterterrorism soldier with a sec...,"Adam Sandler, Zohan Dvir, Emmanuelle Chriqui, ...",You Don't Mess with the Zohan,Released,English,90000000.0,204313400.0,AU
Young Adult,s8792,Movie,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,"Comedies, Dramas, Independent Movies",...,58.0,"Comedy, Drama",A divorced writer from the Midwest returns to ...,"Charlize Theron, Mavis Gary, Patton Oswalt, Ma...",Young Adult,Released,English,12000000.0,22750356.0,AU
Zodiac,s8803,Movie,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers",...,75.0,"Crime, Drama, Mystery, Thriller",A cartoonist teams up with an ace reporter and...,"Jake Gyllenhaal, Robert Graysmith, Mark Ruffal...",Zodiac,Released,English,85000000.0,83080084.0,AU
Zombieland,s8805,Movie,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",...,73.0,"Comedy, Horror",Columbus has made a habit of running from what...,"Woody Harrelson, Tallahassee, Jesse Eisenberg,...",Zombieland,Released,English,23600000.0,102236596.0,AU
Zoom,s8806,Movie,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies",...,54.0,"Family, Comedy, Adventure, Action, Science Fic...",Jack Shepard is an out-of-shape auto shop owne...,"Tim Allen, Jack Sheppard, Courteney Cox, Marsh...",Zoom,Released,English,35000000.0,12506188.0,AU

# Завдання 2

**№1 Створити 2 двовимірні масиви і виконати математичні операції над нимим**

In [38]:
n = 3 # порядковий номер в журналі
matrix_size = n + 2

m1 = np.random.randint(0,10, size=(matrix_size, matrix_size)) # створення двовимірного масиву
m2 = np.random.randint(0,10, size=(matrix_size, matrix_size))

print("Матриця 1")
print(m1)
print("Матриця 2")
print(m2)

Матриця 1
[[9 1 6 8 3]
 [9 6 8 1 8]
 [4 1 4 3 8]
 [0 3 0 8 3]
 [0 6 9 0 9]]
Матриця 2
[[8 9 9 0 9]
 [0 1 7 0 1]
 [2 0 5 8 2]
 [6 8 7 2 6]
 [9 9 6 9 3]]

In [39]:
sum = m1 + m2
print(sum)

[[17 10 15  8 12]
 [ 9  7 15  1  9]
 [ 6  1  9 11 10]
 [ 6 11  7 10  9]
 [ 9 15 15  9 12]]

In [40]:
sub = m1 - m2
print(sub)

[[ 1 -8 -3  8 -6]
 [ 9  5  1  1  7]
 [ 2  1 -1 -5  6]
 [-6 -5 -7  6 -3]
 [-9 -3  3 -9  6]]

In [41]:
div = m1 / m2
print(div)

[[1.125      0.11111111 0.66666667        inf 0.33333333]
 [       inf 6.         1.14285714        inf 8.        ]
 [2.                inf 0.8        0.375      4.        ]
 [0.         0.375      0.         4.         0.5       ]
 [0.         0.66666667 1.5        0.         3.        ]]

/var/folders/wc/tdyl7_yx17nf6rpbtzbkxdpr0000gn/T/ipykernel_10391/3590165937.py:1: RuntimeWarning: divide by zero encountered in divide
  div = m1 / m2

In [42]:
s_mul = m1 * 5 # скалярне множення
print(s_mul)

[[45  5 30 40 15]
 [45 30 40  5 40]
 [20  5 20 15 40]
 [ 0 15  0 40 15]
 [ 0 30 45  0 45]]

In [44]:
v_mul = np.dot(m1,m2) # векторне множення
print(v_mul)

[[159 173 192  91 151]
 [166 167 218 138 133]
 [130 133 132 110  87]
 [ 75  94  95  43  60]
 [ 99  87 141 153  51]]

In [47]:
v = np.linalg.det(m1) # визначник
print(v)

-23049.000000000025

In [48]:
d = np.linalg.eig(m1) # власні числа та вектори
print(d)

EigResult(eigenvalues=array([23.24358111+0.j        , -3.49862661+0.j        ,
        4.64023684+4.37108104j,  4.64023684-4.37108104j,
        6.97457182+0.j        ]), eigenvectors=array([[ 0.42431931+0.j        ,  0.29039236+0.j        ,
         0.23841182+0.52821411j,  0.23841182-0.52821411j,
        -0.67509235+0.j        ],
       [ 0.63050377+0.j        , -0.15519457+0.j        ,
         0.62825501+0.j        ,  0.62825501-0.j        ,
        -0.47561724+0.j        ],
       [ 0.36057816+0.j        , -0.72364669+0.j        ,
        -0.19024754+0.0852288j , -0.19024754-0.0852288j ,
         0.20130946+0.j        ],
       [ 0.22119505+0.j        , -0.11489804+0.j        ,
        -0.29912184-0.10013671j, -0.29912184+0.10013671j,
        -0.11351811+0.j        ],
       [ 0.49343111+0.j        ,  0.59558445+0.j        ,
        -0.14736028-0.32368339j, -0.14736028+0.32368339j,
         0.5144188 +0.j        ]]))

**№2 для заданої функції (1/ ln x x) визначити: похідну (в заданій точці), первісну (на заданому проміжку), а також виконати оптимізацію (визначити глобальний і локальний мінімуми).**

In [51]:
import scipy
import scipy.integrate as integrate
import scipy.optimize as optimize

In [53]:
def f(x):
    return 1 / (x * np.log(x)) # функція

In [54]:
x0 = 2 # координати точки для визначення похідної
derivative = optimize.approx_fprime(x0, f, 1e-6) # визначення похідної 
print(f"Похідна у точці {x0}: {derivative[0]:.4f}")

Похідна у точці 2: -0.8810

In [55]:
a,b = 1.5, 3.0 # проміжок для пошуку первсіної
integral_val, error = integrate.quad(f, a, b) # пошук первісної
print(f"Значення інтеграла на проміжку [{a}, {b}]: {integral_val:.4f}")

Значення інтеграла на проміжку [1.5, 3.0]: 0.9968

In [56]:
local_min = optimize.minimize(f, x0=2.0)
print(f"\nЛокальний мінімум знайдено в точці x = {local_min.x[0]:.4f}")
print(f"Значення функції в цій точці: {local_min.fun:.4f}")

Локальний мінімум знайдено в точці x = 163.2888
Значення функції в цій точці: 0.0012

In [57]:
bounds = [(1.5, 5.0)] 
global_min = optimize.differential_evolution(f, bounds)
print(f"\nГлобальний мінімум знайдено в точці x = {global_min.x[0]:.4f}")
print(f"Значення функції в цій точці: {global_min.fun:.4f}")

Глобальний мінімум знайдено в точці x = 5.0000
Значення функції в цій точці: 0.1243

**№3 Створити масив і словник. Над даним одновимірним масивом виконати операції для роботи з об’єктами Pandas.Series.**

In [59]:
data_list = [8, 43, np.nan, 8]
custom_labels = ['a', 'b', 'c', 'd']
my_series = pd.Series(data=data_list, index=custom_labels) # створення одновимірного масисву
print(my_series)

a     8.0
b    43.0
c     NaN
d     8.0
dtype: float64

In [61]:
my_dict = {'Квіти':200, 'Дерева': 28, 'Кущі': None, 'Трави': 300}
dict_series = pd.Series(my_dict) # створення Series через словник
print(dict_series)

Квіти     200.0
Дерева     28.0
Кущі        NaN
Трави     300.0
dtype: float64

In [62]:
dict_series['Квіти'] # Значення за міткою

np.float64(200.0)

In [63]:
dict_series[dict_series > 100] # фільтрація

Квіти    200.0
Трави    300.0
dtype: float64

In [64]:
dict_series[dict_series.notnull()] # не нульові значення

Квіти     200.0
Дерева     28.0
Трави     300.0
dtype: float64

In [65]:
dict_series[dict_series.isnull()] # нульові значення

Кущі   NaN
dtype: float64